version: "3.8"
services:
  frontend:
    build: ./www
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
  backend:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
    - NODE_ENV=production
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  caddy:
    image: caddy:2
    ports:
      - "8080:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_started
